import logging
from typing import Optional

from fastapi import APIRouter, HTTPException, Body

from ..models.schemas import SignalApproveRequest, SignalModifyRequest, SignalSchema, StageFromBacktestRequest, ExecutionMode
from ..services import signal_queue as sq
from ..services import alert_service as alerts
from ..services import position_tracker as pt
from ..services.exchange_router import get_exchange_client
from ..services.crypto_scanner import _pending_for as _crypto_pending

log = logging.getLogger(__name__)
router = APIRouter(prefix="/api/signals", tags=["signals"])

# Coinbase spot product suffixes — used to route signals to Coinbase
_COINBASE_SUFFIXES = ("-USD", "-USDC", "-USDT", "-EUR", "-GBP")


def _is_coinbase_signal(market_id: str) -> bool:
    return any(market_id.upper().endswith(s) for s in _COINBASE_SUFFIXES)


def _infer_exchange(market_id: str) -> str:
    if _is_coinbase_signal(market_id):
        return "coinbase"
    return "kalshi"  # default for prediction markets


def _asset_type(exchange: str) -> str:
    if exchange == "yahoo":
        return "stock"
    if exchange == "coinbase":
        return "crypto"
    return "prediction_market"


def _derive_target(req: StageFromBacktestRequest) -> float:
    """Estimate a forward price target from the backtest params."""
    if req.exit_threshold is not None:
        if req.exchange == "yahoo":
            # exit_threshold is a % gain (e.g. 0.10 = 10% above entry)
            return round(req.last_price * (1.0 + req.exit_threshold), 4)
        # prediction market: exit_threshold is the target probability
        return req.exit_threshold
    # Fallback: project the average per-trade return
    avg_trade = req.total_return / max(req.total_trades, 1) / 100.0
    return round(req.last_price * (1.0 + avg_trade), 4)


def _derive_confidence(win_rate: float, sharpe: float) -> float:
    """Blend win-rate and Sharpe into a 0–1 confidence score."""
    sharpe_norm = min(sharpe / 3.0, 1.0)          # 3.0 Sharpe → full marks
    raw = win_rate * 0.6 + sharpe_norm * 0.4
    return round(min(max(raw, 0.05), 0.95), 3)


@router.post("/from-backtest", response_model=dict)
async def stage_from_backtest(req: StageFromBacktestRequest):
    """Create a signal directly from a completed backtest result."""
    entry   = req.last_price
    target  = _derive_target(req)
    shares  = req.capital / entry
    edge    = (target - entry) / entry          # expected % gain
    conf    = _derive_confidence(req.win_rate, req.sharpe_ratio)

    reasoning = (
        f"Staged from {req.strategy} backtest on {req.market_title}. "
        f"Return {req.total_return:+.1f}% · Sharpe {req.sharpe_ratio:.2f} · "
        f"Win rate {req.win_rate*100:.0f}% over {req.total_trades} trades. "
        f"Capital ${req.capital:,.0f} → {shares:.4f} units @ {entry:.4f}."
    )

    sig = SignalSchema(
        market_id       = req.market_id,
        strategy        = req.strategy,
        side            = "BUY",
        entry_price     = round(entry, 4),
        target_price    = target,
        stop_loss       = req.stop_loss,
        suggested_size  = int(req.capital),
        suggested_shares= round(shares, 6),
        expected_edge   = round(edge, 4),
        maker_edge      = 0.0,
        delta_taker     = 0.0,
        confidence      = conf,
        reasoning       = reasoning,
        execution_mode  = req.execution_mode,
        exchange        = req.exchange,
        asset_type      = _asset_type(req.exchange),
    )

    # Auto mode: mark as auto_executed immediately (no human review step)
    if req.execution_mode == ExecutionMode.auto:
        sig.status = "auto_executed"

    added = sq.add_signal(sig)
    log.info(
        "Staged signal from backtest: %s %s %.4f  size=$%d  mode=%s",
        req.strategy, req.market_id, entry, int(req.capital), req.execution_mode,
    )
    return {"status": "staged", "signal": added}


@router.get("")
async def list_signals(status: Optional[str] = None):
    """List signals filtered by status. Valid values: pending | approved | rejected"""
    if status == "pending":
        return {"signals": sq.get_pending()}
    if status in ("approved", "executed"):
        return {"signals": sq.get_executed()}
    if status == "rejected":
        return {"signals": sq.get_rejected()}
    return {
        "signals": {
            "pending": sq.get_pending(),
            "approved": sq.get_executed(),
            "rejected": sq.get_rejected(),
        }
    }


@router.get("/alerts")
async def get_alerts():
    """Get all in-app alerts generated by ALERT ONLY mode."""
    return {"alerts": alerts.get_alerts()}


@router.post("/alerts/{alert_id}/read")
async def mark_alert_read(alert_id: str):
    ok = alerts.mark_read(alert_id)
    if not ok:
        raise HTTPException(status_code=404, detail="Alert not found")
    return {"status": "ok"}


@router.post("/{signal_id}/approve")
async def approve_signal(
    signal_id: str,
    body: SignalApproveRequest = Body(default=SignalApproveRequest()),
):
    sig = sq.approve_signal(signal_id, modified_size=body.modified_size)
    if sig is None:
        raise HTTPException(status_code=404, detail="Signal not found or not pending")

    # ── Coinbase crypto signal → place real order ──────────────────────────
    if _is_coinbase_signal(sig.market_id):
        client = get_exchange_client("coinbase")
        if client is None:
            raise HTTPException(status_code=503, detail="Coinbase client not configured")

        size_usd = float(body.modified_size or sig.suggested_size)
        shares   = size_usd / sig.entry_price  # fractional crypto

        try:
            order = await client.place_order(
                product_id=sig.market_id,
                side=sig.side,               # "BUY" or "SELL"
                size=shares,                 # base_size (crypto units)
                limit_price=sig.entry_price if sig.execution_mode.value == "confirm" else None,
            )
        except Exception as exc:
            log.error("Coinbase order failed for signal %s: %s", signal_id, exc)
            raise HTTPException(status_code=502, detail=f"Coinbase order failed: {exc}")

        # Clear crypto scanner pending flag so it can signal again
        _crypto_pending.discard(sig.market_id)

        # Record as a position in tracker (adapts to crypto scale)
        pos = pt.open_position(sig, exchange="coinbase")
        log.info(
            "Coinbase order placed: %s %s %.8f @ %.4f  order_id=%s  pos=%s",
            sig.market_id, sig.side, shares, sig.entry_price,
            order.get("order_id", "?"), pos["id"],
        )
        return {
            "status":     "approved",
            "exchange":   "coinbase",
            "signal":     sig,
            "position_id": pos["id"],
            "order":      order,
            "shares":     round(shares, 8),
            "size_usd":   size_usd,
        }

    # ── Prediction market signal → existing flow ───────────────────────────
    pos = pt.open_position(sig, exchange=_infer_exchange(sig.market_id))
    log.info("Approved signal %s  size=%d  position=%s", signal_id, sig.suggested_size, pos["id"])
    return {"status": "approved", "signal": sig, "position_id": pos["id"]}


@router.post("/{signal_id}/reject")
async def reject_signal(signal_id: str):
    sig = sq.reject_signal(signal_id)
    if sig is None:
        raise HTTPException(status_code=404, detail="Signal not found or not pending")
    log.info("Rejected signal %s", signal_id)
    return {"status": "rejected", "signal": sig}


@router.post("/{signal_id}/modify")
async def modify_signal(signal_id: str, body: SignalModifyRequest):
    sig = sq.modify_signal(signal_id, size=body.size, price=body.price)
    if sig is None:
        raise HTTPException(status_code=404, detail="Signal not found or not pending")
    log.info("Modified signal %s  size=%d", signal_id, body.size)
    return {"status": "modified", "signal": sig}
